export default {
  modal: document.querySelector('.backdrop'),
  modalContent: document.querySelector('.modal'),
  modalCloseBtn: document.querySelector('[data-modal-close]'),
  mainGalleryEl: document.querySelector('.container-main-gallery'),
  mainGalleryTitleEl: document.querySelector('.category-title'),
  mainGalleryTitleSpanEl: document.querySelector('.category-title-span'),
  categoriesList: document.querySelector('.categories-list'),
  userLoginBtn: document.querySelector('.user-login'),
  authFormBackdrop: document.querySelector('.auth-backdrop'),
  authFormCloseBtn: document.querySelector('.auth-form-close-btn'),
  authForm: document.querySelector('.js-register-form'),
  supportEl: document.querySelector('.support-container'),
  supportRenderEl: document.querySelector('.support-render'),
  iconSvgBtnEl: document.querySelector('.support-icon'),
  supportLoadBtn: document.querySelector('.support-button'),
  footerProfilesEl: document.querySelector('.profile-list'),
  pixelJsCakeBtn: document.querySelector('.pixel-js-cake-btn'),
  spinnerEl: document.querySelector('.breeding-rhombus-spinner'),
  wrapperBookEl: document.querySelector('.wrapper-book'),
  buttonAddBookEl: document.querySelector('.form__button'),
  addedTextEl: document.querySelector('.added-text'),
  // buttonDeleteBookEl: document.querySelector('.deleteBook'),
  //form
  signUpFormBtn: document.getElementById('signup-formbtn'),
  loginFormBtn: document.getElementById('signin-formbtn'),
  nameInput: document.getElementById('uname'),
  emailInput: document.getElementById('uemail'),
  passwordInput: document.getElementById('upassword'),
  btnLogin: document.getElementById('btnLogin'),
  btnSignup: document.getElementById('btnSignup'),
  btnLogout: document.getElementById('btnLogout'),
  authSubmitBtn: document.getElementById('authform-submitBtn'),
  //login
  profileNameEl: document.querySelector('[data-profile-name]'),
  headerProfileEl: document.getElementById('header-profile-btn'),
  headerSignupEl: document.getElementById('header-signup'),
  headerlogoutBtn: document.getElementById('header-logout'),
  //shopping-list
  shoppingList: document.querySelector('.shopping-list-js'),
  emptyList: document.querySelector('.empty-list-js'),
};
