export default {
  mainGalleryEl: document.querySelector('.container-main-gallery'),
  mainGalleryTitleEl: document.querySelector('.category-title'),
  mainGalleryTitleSpanEl: document.querySelector('.category-title-span'),
  categoriesList: document.querySelector('.categories-list'),
  userLoginBtn: document.querySelector('.user-login'),
  authFormBackdrop: document.querySelector('.auth-backdrop'),
  authFormCloseBtn: document.querySelector('.auth-form-close-btn'),
  authForm: document.querySelector('.js-register-form'),
  supportEl: document.querySelector('.support-container'),
  supportLoadBtn: document.querySelector('.support-button'),
  footerProfilesEl: document.querySelector('.profile-list'),
  pixelJsCakeBtn: document.querySelector('.pixel-js-cake-btn'),
  spinnerEl: document.querySelector('.breeding-rhombus-spinner'),
  //form
  signUpFormBtn: document.getElementById('signup-formbtn'),
  loginFormBtn: document.getElementById('signin-formbtn'),
  emailInput: document.getElementById('uemail'),
  passwordInput: document.getElementById('upassword'),
  btnLogin: document.getElementById('btnLogin'),
  btnSignup: document.getElementById('btnSignup'),
  btnLogout: document.getElementById('btnLogout'),
  authSubmitBtn: document.getElementById('authform-submitBtn'),
};
